#!/bin/env bash
flags="-Wall -Weffc++ -Wextra -Wconversion -Wsign-conversion -Werror -pedantic-errors -std=c++17"

if [[ $2 = "debug" ]]; then
    echo "Compiling with debug flags"
    debugFlags="-g"
else
    debugFlags="-O2 -DNDEBUG"
fi

sh -c "g++ $flags $debugFlags $1 -o main && ./main"